name: the_melophiles
description: "Our Music App For All"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_masonry_view: ^0.0.2
  lottie: ^1.3.0
  animated_text_kit: ^4.3.0
  cupertino_icons: ^1.0.8
  flutter_animated_icons: ^1.0.1
  iconsax: ^0.0.8
  marquee: ^2.3.0
  google_fonts: ^6.3.2

  # State / Navigation
  get: ^4.7.2

  # AUDIO & METADATA
  just_audio: ^0.10.5
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.12
  on_audio_query: ^2.9.0
  audio_session: 0.1.25

  # Storage / DB
  image_picker: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  # Permissions / System
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  package_info_plus: ^9.0.0

  # Music
  audio_wave: ^0.1.5
  palette_generator: ^0.3.3+7
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/snoopy_icon.jpg"
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/snoopy_icon.jpg"